package framework;

public enum ScriptState {
    DETERMINE_PROGRESSION_TASK,
    DETERMINE_MONEY_MAKING_TASK,
    ENSURE_LOAD_OUT,
    BUY_ITEMS,
    SELL_ITEMS,
    BANKING,
    WOODCUTTING_TRAINING,
    MINING_TRAINING,
    MELEE_TRAINING,
    RANGED_TRAINING,
    FISHING_TRAINING,
    THE_RESTLESS_GHOST,
    COOKS_ASSISTANT,
}
