package framework;

/**
 * - ProgressionTask 1st, MoneyMakingTask 2nd
 */
public enum ScriptState {
    WOODCUTTING_TRAINING, // ProgressionTask - Training
    MINING_TRAINING,
    MELEE_TRAINING,
    RANGED_TRAINING,
    FISHING_TRAINING,
    RUNECRAFT_TRAINING,
    THE_RESTLESS_GHOST, // ProgressionTask - Questing
    COOKS_ASSISTANT,
    RUNE_MYSTERIES,
    X_MARKS_THE_SPOT,
    PIRATES_TREASURE,
    WITCHS_POTION,
    ERNEST_THE_CHICKEN,
    THE_KNIGHTS_SWORD,
    MISTHALIN_MYSTERY,
    SPINNING_BALLS_OF_WOOL, // MoneyMakingTask
    SMELTING_BRONZE_BARS,
    SMELTING_STEEL_BARS,
    CHOPPING_LOGS,
    INITIALIZE_SCRIPT, // Utility
    DETERMINE_TASK,
    INITIALIZE_TASK,
    BUY_ITEMS,
    SELL_ITEMS,
    BANKING,

}
